### ISSUE TITLE
Vex Mixen

### ISSUE THREAD

**Issue by adamschwartz** [HubSpot/vex#1]
Would be great to get a [MIxen](https://github.com/HubSpot/Mixen) for Vex, similar to the [one we now have internally](https://git.hubteam.com/HubSpot/vex/blob/master/static/js/mixin.coffee).

Placeholder for @gregsabo.

**Comment by bbatliner** [comment]
Hm, not sure what this is about, but our [plugin system](http://github.hubspot.com/vex/api/plugins/) probably accomplishes something similar.
