### ISSUE TITLE
Position dialog in certain location

### ISSUE THREAD

**Issue by cprcrack** [HubSpot/vex#101]
Is it possible to absolutely position a dialog in a certain position, such as right below the button that fires the dialog?

The idea is that it looks more like a menu for that button. Or alternatively, do you know about any other framework suitable for my use case?

**Comment by adamschwartz** [comment]
That’s exactly what we built Tether ([GitHub](https://github.com/HubSpot/tether), [Docs](http://github.hubspot.com/tether/docs/welcome/)) and Drop ([GitHub](https://github.com/HubSpot/drop), [Docs](http://github.hubspot.com/drop/docs/welcome/)) for. :)
