### ISSUE TITLE
Disable submit button until input in prompt matches value

### ISSUE THREAD

**Issue by danieljacobarcher** [HubSpot/vex#107]
I'm sure this has come up before, but couldn't find any answers..

I want to be able to pass in a value that the prompt compares against, before enabling the submit button. Could be using a regex for this as an option in the prompt options hash?

**Comment by adamschwartz** [comment]
We’ve had people ask many times about how to preventing the modal from closing, but actually, to my knowledge nobody has specifically asked about disabling the submit button.

If you’d an answer to the former, check out https://github.com/HubSpot/vex/issues/87. If you specifically are interested in a solution for disabling the submit button when the input value is empty, you could do something like this:

```coffeescript
vex.dialog.prompt
    className: 'vex-theme-default'
    message: 'Enter a non-empty value:'
    afterOpen: ($vexContent) ->
        $submit = $vexContent.find('button[type="submit"]')
        $submit.attr 'disabled', true
        $vexContent.find('input').on 'input', ->
            if $(this).val()
                $submit.removeAttr 'disabled'
            else
                $submit.attr 'disabled', true
```

[Demo on jsFidde](http://jsfiddle.net/adamschwartz/px81taeq/)

**Comment by danieljacobarcher** [comment]
Thanks @adamschwartz! That's what I was looking for. I didn't realize that afterOpen was available to prompt, I thought it was only for Open.

**Comment by adamschwartz** [comment]
@danieljacobarcher no problem! Happy to help.

Yeah, basically all of the options you pass to the `vex.dialog.___` calls (`alert`, `confirm`, `prompt`, and `open`) [pass their options through to `vex.open`](https://github.com/HubSpot/vex/blob/0cfe0a8c6c0692e4d32df15044aff653053d5161/coffee/vex.dialog.coffee#L62). This includes any of the `defaultOptions` listed in the [docs](http://github.hubspot.com/vex/api/advanced/). I can try to make this more clear in the docs. Thanks!
