### ISSUE TITLE
`beforeClose` option: way to prevent actual close event?

### ISSUE THREAD

**Issue by banderson** [HubSpot/vex#114]
Hello there! I'm working on a React version for vex at HubSpot, and was looking for a way to prevent vex from closing itself in certain circumstances (it's pretty much required when using the declarative nature or React). The first thing I thought of was [return false from `beforeClose` hook](https://github.com/HubSpot/vex/compare/master...banderson:master?diff=unified&name=master), since there is no `event` object on which I can call `preventDefault`. 

Does that sound like a reasonable thing?

For `vex.dialog` usage, that effectively means returning false from the `callback` option. I'm not sure how If that's explicit enough, so looking to see what you think.

**Comment by adamschwartz** [comment]
Cool! Vex React would be a wonderful thing. :)

With respect to `vex.dialog` [this is always the answer I gave](https://github.com/HubSpot/vex/issues/59#issuecomment-43928824).

As for `vex`, I’m not sure what you mean by “prevent vex from closing itself.” Do you mean when one’s code calls `vex.close()`. Or do you mean when `vex.close()` is called internally by vex? Something else entirely or perhaps both? I’d probably have slightly different answers for each of these so let me know.

**Comment by banderson** [comment]
@adamschwartz thanks for the response! 

I'm referring to when vex calls close internally (e.g. on `escape` press, clicking away, or the event handlers on the buttons setup in the config). 

The main use case is: In React, everything is done declaratively, so we need to pass in an `isOpen` argument that should dictate whether the dialog should currently be open. When one clicks away or on one of the buttons, vex closes itself, leaving the program in conflicted state (i.e. `isOpen` could still be set to true). 

What I'm looking to do is to tap into the `beforeClose` hook to prevent the auto-close behavior in certain cases. Hopefully that makes sense...

**Comment by adamschwartz** [comment]
Yeah, totally makes sense. I’d say go for it!

**Comment by phstc** [comment]
> Hello there! I'm working on a React version for vex at HubSpot


Hey

Probably there are better ways to do that, but here's how I'm using vex with [React](https://facebook.github.io/react/) and [Riot](https://muut.com/riotjs/):

React:

```coffeescript

@ProfileShow = React.createClass
  propTypes:
    name: React.PropTypes.string
    image: React.PropType.string

  dialog: (e) ->
    vex.open
      profileShow: this,
      afterOpen: ($modal) ->
        React.render(`<ProfileShowDialog name={this.themePreview.props.name}`, $modal[0])

  render: ->
    `<div onClick={this.dialog}>
       <a href="javascript:void(0)">
         <img src={this.props.image}/>
       </a>
    </div>`


@ProfileShowDialog = React.createClass
  propTypes:
    name: React.PropTypes.string

  render: ->
    `<p>{this.props.name}</p>`
```

Riot:

```html
<profile-show>
  <div onclick={ dialog }>
    <a href="javascript:void(0)">
      <img src={ opts.image }>
    </a>
  </div>

    <script>
      dialog(e) {
        vex.open({
          tag: this,
          afterOpen: function($modal) {
            riot.mountTo($modal[0], 'profile-show-dialog',
              { name: this.tag.opts.name })
          }
        });
      }
    </script>
</profile-show>

<profile-show-dialog>
  <p>{ this.props.name }</p>
</profile-show-dialog>
```

I'm not passing `content: ` to the dialogs, instead I'm rendering a component/tag on its container. I've never liked the way I used to pass the content to vex dialogs, which was usually by grabbing the contents of a hidden div or a `script type="text/template"`. I'm kind of liking rendering a component on its content, it feels more correct IMO.

What do you guys think about it?

I can add (PR) these examples in docs, in case them make sense.

**Comment by banderson** [comment]
@phstc I agree with you about passing in `content` in that way, it doesn't feel right in the react world. I also got a lot of mileage out of the pattern you listed above for React. The issue we ran into is that for more complex use cases, our modals really behaved like its own embedded app that needs to manage its own lifecycle. (e.g. what happens when the user accidentally clicks away midway through filling out a form?) We wanted to give power users a way to prevent that from happening.

We've been working on a React vex project for a while, perhaps we'll get to share it soon :)

**Comment by phstc** [comment]
> what happens when the user accidentally clicks away midway through filling out a form?

would something like that:

```coffeescript
  dialog: (e) ->
    vex.open
      profileShow: this,
      afterOpen: ($modal) ->
        this.profileShowDialog = React.render(`<ProfileShowDialog name={this.profileShow.props.name}`, $modal[0])
      beforeClose: ($modal) ->
        return this.profileShowDialog.allFilled() 
```

help with that?


> we'll get to share it soon :)

I'm looking forward to it :smile:  I can use some of what you've done for React for Riot as well.

**Comment by banderson** [comment]
That idea of returning `false` from `beforeClose` was exactly what I needed to add in this PR in order to get things working. Without that we were stuck. So yes, that setup will work nicely for you. However, we added more functionality and turned it into a declarative API like:

```html
render() {
  return <Alert header="Alert!" message="You cannot proceed!" isOpen={bool} />;
}
```

and a more advanced set of components that allows full control over content and component lifecycle: 

```html
<Dialog isOpen={bool} afterClose={fn} callback={fn}>
  <Header>Dialog sub-components</Header>
  <Body>
    <Message>
      <h1>Anything You Want</h1>
      <img src="..." />
    </Message>
    <Inputs>
      <input ref="name" type="text" />
      <input ref="email" type="text" />
    </Inputs>
  </Body>
  <Footer>
    <Button use="primary" onClick={this.doSomething}>Ok</Button>
    <Button use="secondary" onClick={this.cancel}>Cancel</Button>
  </Footer>
</Dialog>
```

And some helpers for creating multi-step wizard interfaces:

```html
<Wizard isOpen={bool}>
  <Step ...>
  <Step ...>
<Wizard>
```

**Comment by jackyon** [comment]
when is the react version released? can't wait for this ;)
