### ISSUE TITLE
Making dialogs moveable?

### ISSUE THREAD

**Issue by ausrussell** [HubSpot/vex#115]
Am really liking vex, cheers!
Has there been any thought or work put into making the dialogs moveable? It's a requirement for the site I work on and I'd appreciate any guidance. I've had a look at the CSS and at first glance it looks like it might require significant changes.... am considering trying jQuery draggable.

**Comment by adamschwartz** [comment]
jQuery draggable should work, but depending on your browser requirements, you may be able to get away with the HTML draggable property and some JS. I whipped up a little [demo in jsFiddle](http://jsfiddle.net/adamschwartz/hw8q4wnp/).

Source:

```javascript
var $vexContent = vex.dialog.alert({
    closeOnOverlayClick: false,
    message: 'Drag me'
});

$vexContent.attr('draggable', true);

$vexContent[0].addEventListener('dragstart', function(event) {
    var style, boundingClientRect, data;
    style = window.getComputedStyle($vexContent[0]);
    boundingClientRect = $vexContent[0].getBoundingClientRect();
    data = (parseInt(style.getPropertyValue('left'),10) - event.clientX) + ',' + (parseInt(style.getPropertyValue('top'),10) - event.clientY);
    if (style.getPropertyValue('left') === 'auto') {
        data = (- event.clientX) + ',' + (- event.clientY);
    }
    event.dataTransfer.setData('text/plain', data);
}, false);

document.body.addEventListener('dragover', function(){ 
    event.preventDefault(); 
    return false; 
}, false);

document.body.addEventListener('drop', function(event) { 
    var offset = event.dataTransfer.getData('text/plain').split(',');
    $vexContent[0].style.left = (event.clientX + parseInt(offset[0], 10)) + 'px';
    $vexContent[0].style.top = (event.clientY + parseInt(offset[1], 10)) + 'px';
    event.preventDefault();
    return false;
}, false); 

```

**Comment by softpacks** [comment]
Just include the jquery user interface library (jquery-ui.js) in your project. Then make the Vex dialog draggable by calling the draggable method on the vex dialog variable (e.g myvexdiag.draggable).

Cheers.

**Comment by markstos** [comment]
@softpacks In the changes proposed in #160, vex.open would not be returning a jQuery object, but it's an own object. I presume this means the `draggable()` method would automatically be available.

**Comment by bbatliner** [comment]
Draggable isn't going to happen natively. If you can find a way to make it work with jQuery go for it.
