### ISSUE TITLE
Promises support?

### ISSUE THREAD

**Issue by EgoAleSum** [HubSpot/vex#118]
It would be nice if Vex could implement promises support. With them, dialogs for example would look much nicer:

Before:

``` javascript
    vex.dialog.confirm({
        message: message,
        callback: function(confirmed) {
            if(confirmed) {
                // Do something
            }
            else {
                // Do something else
            }   
        }
    })
```

With promises:

``` javascript
    vex.dialog.confirm(message)
    .then(function() {
        // Has been confirmed
    }, function() {
        // Not confirmed
    })
```

This could be done without breaking compatibility with the existing APIs.

**Comment by markstos** [comment]
@bbatliner this is another significant feature to consider during the beta period.

According to [caniuse.com](http://caniuse.com/#feat=promises), native promise support is available in 75% of browsers globally and 85% in the US.  So it seems a promise library would needed for now to reach 95% support, but there's hope a dependency on a promise library could be removed later. 

I don't have much of an opinion right now. As a practical matter, or code base uses a mix of callbacks and promises so both are familiar enough.

**Comment by geekjuice** [comment]
While I'm all on board for moving to `Promises`, I do feel a little weird about bringing in a `Promise` library since we just removed the dependency on `jQuery` for `3.0.0`. Having said that, this seems like a great feature to add a plugin 😉

**Comment by markstos** [comment]
That's true. The common use case for vex-3 is using it combination with the dialog plugin.  So making a `dialog-promises` plugin sounds like the way to go to achieve promises for this common case using vex 3.  No PR is required, as plugins can be published independently.

**Comment by bbatliner** [comment]
Hi, there is now a promise plugin for vex-dialog: https://github.com/michaelvdow/vex-dialog-promise

Docs don't exist at the moment but it's fairly self-explanatory and exactly as you wrote your example:

```javascript
vex.registerPlugin(require('vex-dialog-promise'))
vex.dialog.confirm(message)
    .then(function() {
        // Has been confirmed
    }, function() {
        // Not confirmed
    })
```
