### ISSUE TITLE
JQuery Autocomplete

### ISSUE THREAD

**Issue by timi2shoes** [HubSpot/vex#119]
Cannot get autocomplete to work with an input text box. When the suggested text is rendered it does not show up below the input text box. The open event is being called but nothing is shown to the user.

**Comment by adamschwartz** [comment]
Hey @timi2shoes happy to help. Can you please provide some example code and/or a link to a page where we can observe this errant behavior? Thanks for using Vex!

**Comment by timi2shoes** [comment]
Hey Adam,

The code I am using:

function edit_value_modal(value_id) {
    vex.dialog.open({
        message: 'Edit Value:',
        input: '' +
                '<input id="value" type="text" placeholder="Value Name"
required />' +
                '<script>' +
                '$(function () {' +
                '$("#val_holder").autocomplete({' +
                'source: function (request, response) {' +
                '$.ajax({' +
                'url: "/get/autocomplete.ashx",' +
                'data: {' +
                'q: request.term' +
                '},' +
                'success: function (data) {' +
                'response(data);' +
                '}' +
                '});' +
                '},' +
                'minLength: 3' +
                '});' +
                '});' +
                '</script>' +
                '',
        buttons: [
                $.extend({}, vex.dialog.buttons.YES, { text: 'Add' }),
                $.extend({}, vex.dialog.buttons.NO, { text: 'Back' })
        ],
        callback: function (data) {
            if (data !== false) {

            }
        }
    });
}


I can get autocomplete to work on the same page on non vex items and it
works great.

Jquery I am using:
ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.min.css
ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js
ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js


Hope that helps

-Tim

**Comment by timi2shoes** [comment]
I also noticed that when the <ul> is generated if I change the zindex to a
higher number than what vex has it will show up.

**Comment by bbatliner** [comment]
Closing to clean up a little.
