### ISSUE TITLE
popup doesn't disappear when using html history

### ISSUE THREAD

**Issue by franckl** [HubSpot/vex#127]
I have an app with 3 tabs on a single html page using the html history features to change the url for each tab. The 2nd tab opens a vex.dialop.open popup.

When I click on the back button of the browser from the 2nd tab with the vex dialog open, the url changes back to the previous tab and loads it correctly but the vex popup is still displayed.

Is there a way to desactivate the popup ?

**Comment by geekjuice** [comment]
You can probably just override the click handler for the tabs to call `vexInstance.close()` if you have the vex instance or `vex.closeAll()` to close all vex modals.

**Comment by franckl** [comment]
thanks, it works like a charm. I haven't seen closeAll() in the doc

**Comment by geekjuice** [comment]
No problem :smile_cat: Hopefully we'll have the documentation updated to reflect the full API as it does seem like certain methods are missing.
