### ISSUE TITLE
Vex and Pikaday don’t play nicely

### ISSUE THREAD

**Issue by adamschwartz** [HubSpot/vex#129]
https://github.com/dbushell/Pikaday/issues

Ref:
https://twitter.com/tl8roy/status/616058707453964288

**Comment by bbatliner** [comment]
No clue if this is still an issue, but I was able to get vex 3 and Pikaday working together. See code snippet below:

```js
vex.defaultOptions.className = 'vex-theme-wireframe'; // pick any theme
var input = document.createElement('input');
input.type = 'text';
input.value = '9 Aug 2016';
var picker = new Pikaday({
    field: input,
    format: 'D MMM YYYY',
    onSelect: function() {
        console.log(picker.toString());
    }
});
vex.open({
    unsafeContent: input
});
```

I don't know what the use case was a year ago. If it's still of concern, I'd be happy to help.

**Comment by adamschwartz** [comment]
+ @tl8roy

**Comment by tl8roy** [comment]
I will have to update everything to really check. When I am working on that project again I will test this.

**Comment by bbatliner** [comment]
Assuming this is still working. Thanks all.
