### ISSUE TITLE
Does vex have the notion of inline content?

### ISSUE THREAD

**Issue by grofit** [HubSpot/vex#131]
All tuts seem to indicate writing the content within the JS as a string with html in, however is it possible to just pass the content a reference to an existing element, and it would just show that?

I noticed another question where you were recommending cloning of the existing element, the problem is that in this scenario I am using Knockout and I need bindings to carry into the modal, and I think cloning would confuse knockout and make memory leaks.

**Comment by adamschwartz** [comment]
Absolutely:

```javascript
$vexContent = vex.open(); // $vexContent is a jQuery-wrapped reference to the `<div class="vex-content"></div>` node
$vexContent.append(node);
```

Or even more simply:

```javascript
vex.open().append(node);
```

There are more examples in [the docs](http://github.hubspot.com/vex/api/advanced/#basics-of-opening-and-passing-content) as well. Note that if the `node` is already in the DOM, jQuery’s `append` will move it from its current position. This is the primary reason I’ve recommended cloning in the past. But if you’re generating detached DOM nodes in JS, then there is probably no need to clone them before appending.

**Comment by grofit** [comment]
ace, thanks for the info will go give it a try.
