### ISSUE TITLE
CoffeeScript to ES6 conversion

### ISSUE THREAD

**Issue by Setsun** [HubSpot/vex#138]
I've noticed with other HubSpot libraries such as Tether all of the CoffeeScript has been refactored into ES6. Is there an invested interest in moving other libraries such as this over to ES6 and compiling with Babel?

**Comment by geekjuice** [comment]
Yup. At some point (and this has some personal bias), all of our projects will have the same build steps, directory structure, and support. This means - at least for the near future - moving to a common build tool and step (Gulp at the moment), having a `{project}/{src|dist}` project structure, UMD support, updated packages on `npm` and `bower`, and moving from Coffeescript to ES6.

While the current bandwidth to do this for all projects is limited, we are working towards getting our more popular projects (such as __vex__) completed. In addition, we're trying to improving our communication with the OS community in terms of reviewing pull requests and handling issues in a more timely manner. :+1:

**Comment by bbatliner** [comment]
We're currently on ES5/JavaScript with Browserify for bundling. If you're interested in porting to ES6 with Babel, please contribute! Thanks!
