### ISSUE TITLE
Animation end broken

### ISSUE THREAD

**Issue by peacechen** [HubSpot/vex#142]
The latest commit (648c677eba441907d00a6ec4f855c583b49ffcf3) introduced a check for `hasAnimation` which prevents the closing animation from happening.  The logic looks inverted:

```coffeescript
    hasAnimation = $vex.css('animationName') != 'none' && $vex.css('animationDuration') != '0s'

    if animationEndSupport && hasAnimation
       unless beforeClose() is false
             $vex
                .unbind(vex.animationEndEvent).bind(vex.animationEndEvent, -> close())
                .addClass(vex.baseClassNames.closing)

     else
        unless beforeClose() is false
            close()
```

As far as I can understand, the intent is to animate the close if no current animation is running. Otherwise just close it without interrupting the existing animation.  However the logic is inverted such that it won't animate if no current animation is running.  The fix:

```coffeescript
    if animationEndSupport && !hasAnimation
        unless beforeClose() is false
```

**Comment by adamschwartz** [comment]
Thanks for letting us know. We’ll take a look.

**Comment by deansimcox** [comment]
I just ran into this as well, I think the problem is that the hasAnimation check is looking at the vex container for an animation, where it should be looking at the vex-content element instead?
```javascript
hasAnimation = $vexContent.css('animationName') != 'none' && $vexContent.css('animationDuration') != '0s'
```
Might be wrong though?

**Comment by deansimcox** [comment]
I just tried that above and it seemed to work.

Here's a quick monkey patch:

```javascript
		var animationEndSupport = false;
		(function(){
			var s;
			s = (document.body || document.documentElement).style;
			animationEndSupport = s.animation !== void 0 || s.WebkitAnimation !== void 0 || s.MozAnimation !== void 0 || s.MsAnimation !== void 0 || s.OAnimation !== void 0;
			return $(window).bind('keyup.vex', function(event) {
				if (event.keyCode === 27) {
					return vex.closeByEscape();
				}
			});
		}());
		
		vex._closeByID = vex.closeByID;

		vex.closeByID = function(id) {
			var $vex, $vexContent, beforeClose, close, hasAnimation, options;
			$vexContent = vex.getVexByID(id);
			if (!$vexContent.length) {
				return;
			}
			$vex = $vexContent.data().vex.$vex;
			options = $.extend({}, $vexContent.data().vex);
			beforeClose = function() {
				if (options.beforeClose) {
					return options.beforeClose($vexContent, options);
				}
			};
			close = function() {
				$vexContent.trigger('vexClose', options);
				$vex.remove();
				$('body').trigger('vexAfterClose', options);
				if (options.afterClose) {
					return options.afterClose($vexContent, options);
				}
			};
			hasAnimation = $vexContent.css('animationName') !== 'none' && $vexContent.css('animationDuration') !== '0s';
			if (animationEndSupport && hasAnimation) {
				if (beforeClose() !== false) {
					$vex.unbind(vex.animationEndEvent).bind(vex.animationEndEvent, function() {
						return close();
					}).addClass(vex.baseClassNames.closing);
				}
			} else {
				if (beforeClose() !== false) {
					close();
				}
			}
			return true;
		};
```

**Comment by peacechen** [comment]
Bump

Any plans to integrate deansimcox's fix?

**Comment by adamschwartz** [comment]
Someone just needs to make a PR. Of course it was a PR (https://github.com/HubSpot/vex/pull/139) which caused the issue in the first place... :stuck_out_tongue:

**Comment by deansimcox** [comment]
No worries, I'll make  pull request when I get a chance.

**Comment by adamschwartz** [comment]
Thanks @deansimcox

**Comment by deansimcox** [comment]
Finally got round to this! See the references above

**Comment by peacechen** [comment]
Thanks for fixing this. Any chance you could publish the new version on npm?

**Comment by deansimcox** [comment]
@peacechen Sure, what's the process for publishing to npm - Is it just running the command 'npm publish' ?

**Comment by peacechen** [comment]
@deansimcox
Basically yes, but make sure the npm credentials on your box are set correctly.  The package.json also needs its version field updated to match the version being released.
https://gist.github.com/coolaj86/1318304

Vex-js 2.3.3 is currently published on npm's registry by geekjuice.  It would be best if the update was published by the same users.
https://www.npmjs.com/package/vex-js

**Comment by geekjuice** [comment]
@deansimcox @peacechen `vex-js@v2.3.4` should be published on npm now :+1:

**Comment by deansimcox** [comment]
Sweet! cheers guys

**Comment by jybleau** [comment]
Hi @deansimcox @peacechen @geekjuice 

Can someone create a new release of the 2.3.4 on github so Bower could offer this version?

Related to: [https://github.com/HubSpot/vex/issues/151](https://github.com/HubSpot/vex/issues/151)

**Comment by geekjuice** [comment]
Just pushed the `v2.3.4` tag. Should be available on bower. Thanks for the heads up that it wasn't published :sweat_smile:

**Comment by jybleau** [comment]
No problem. Thank you, it works now.
