### ISSUE TITLE
pace-theme-center-atom.css not work with bootstrap

### ISSUE THREAD

**Issue by dcy** [HubSpot/vex#143]
pace-theme-center-atom.css not work with bootstrap

![2015-11-25-003420_148x141_scrot](https://cloud.githubusercontent.com/assets/1137238/11373446/505e71bc-930d-11e5-9c7b-b7e08844cbc7.png)

**Comment by adamschwartz** [comment]
Mmm I’ve seen this before. I believe it’s a `box-sizing` issue. I think you probably meant to add this to https://github.com/HubSpot/pace/issues though, yeah?

**Comment by dcy** [comment]
Yes, Sorry! It is pace's issue
