### ISSUE TITLE
vex.dialog.alert and data attributes with numeric values

### ISSUE THREAD

**Issue by cpgo** [HubSpot/vex#150]
Maybe I missed something in the docs but here we go:
When I try to call `vex.dialog.alert($(this).data('something'))` if `something` is a number the alert's text is simply "Alert"

What I did was calling `.toString()` on the result to get it working. Is this intended?

Edit: I belive this is the reason: 
https://github.com/HubSpot/vex/blob/master/js/vex.dialog.js#L60
https://github.com/HubSpot/vex/blob/master/js/vex.dialog.js#L83

**Comment by bbatliner** [comment]
This looks like an issue from vex 2 or earlier. Please upgrade to the latest version and let me know if you are still experiencing any issues. Thank you for using vex!
