### ISSUE TITLE
Not firing "close" event, so no close animation

### ISSUE THREAD

**Issue by belisarius** [HubSpot/vex#151]
I've been working on a pretty simple implementation of Vex and everything's going fine, except that for some reason it appears to be not firing the "close" event, so the "vex-closing" class isn't added, and consequently the "closing" animation isn't triggered: The modal just disappears. My code is the following:

```javascript
        var modalAppend = $('.m_hero');
        var searchActivate = $('button.search-activate');
        searchActivate.click(function() {
            var searchModal = vex.dialog.prompt({
                message: false,
                placeholder: "Enter Keyword",
                className: 'm_modal__search m_modal',
                appendLocation: modalAppend,
                callback: function(value) {
                    if(value!==false){
                        location.href = "/?s=" + encodeURI(value);
                    }
                }
            });
        });  
```

All close methods (clicking modal, clicking cancel, clicking the close button) close the modal, but the close animation never triggers. I'm using custom CSS, but I don't believe that's the problem, since I've watched the inspector while close, and the "vex-closing" class never appears. 

The problem appears in up-to-date versions of both Chrome and Safari. I don't have much other Javascript running on this page, but I've tried disabling it and it didn't have any effect, so I don't think it's about script conflicting with it. Setting up different vex instances outside of that click event behave the same way, so I don't think it's the configuration of this particular item.

Thanks for any help, and let me know if you need anything else!

**Comment by jybleau** [comment]
The problem has been fixed with this issue: 
[https://github.com/HubSpot/vex/issues/142](https://github.com/HubSpot/vex/issues/142)

It was published on npm but not on bower it seems... Did you get the package from Bower? I did and I got the same error.

The error was on line 140 in vex.js: 
https://github.com/HubSpot/vex/blob/master/js/vex.js#L140

It was referring to $vex instead of $vexContent.

**Comment by jybleau** [comment]
npm version is at 2.3.4, which is the latest.

Bower offer only up to 2.3.3.

**Comment by jybleau** [comment]
@belisarius 
2.3.4 tag has been created, it's now available from Bower.
I thinks it fixes your problem. Let us know.

**Comment by belisarius** [comment]
Yes, that did the trick! Thanks a bunch for your help.
