### ISSUE TITLE
Minified version not updated?

### ISSUE THREAD

**Issue by dodas** [HubSpot/vex#156]
It looks like minified version has not been updated to 2.3.4, nor on github, nor on npm.

**Comment by bbatliner** [comment]
I installed version 2.3.4 from npm and also found the minified versions to be at version 2.3.3. I don't think this can be fixed.

However, I recommend checking out the beta of vex 3, which you can get with `npm i vex-js@3.0.0-beta.1`. This repo has been updated, as well as all of the docs. Let me know what you think!
