### ISSUE TITLE
Should use .on instead of .bind

### ISSUE THREAD

**Issue by dodas** [HubSpot/vex#158]
You should be using jquery method `on` instead of `bind`, as it is stated in jquery  [documentation](http://api.jquery.com/bind/): 

> As of jQuery 1.7, the .on() method is the preferred method for attaching event handlers to a document

`bind` will probably be deprecated and removed in future.

**Comment by TrevorBurnham** [comment]
`.on` was added in jQuery 1.7. Some folks still use older versions of jQuery. I don't see a compelling reason to break backward compatibility here.

If we were to move away from `.bind`, it would likely be to get rid of the jQuery dependency altogether.
