### ISSUE TITLE
Is it possible to refresh the dialog window without closing and reopening it?

### ISSUE THREAD

**Issue by cecilylomein** [HubSpot/vex#162]
I'm trying to place a bootstrap image carousel in a vex dialog window, but if I try to navigate between images, the picture won't change until I close and reopen the dialog. Is there any way to force the dialog message to reload?

``` javascript
var d = $(this).children('.my-dialog'); // getting content from hidden div
vex.dialog.open({
  message: d.html(),
  buttons: [],
  afterOpen: function() {
    $('.carousel-control').click(function() {
      // i want to update the dialog window here
    });
  }
});
```

Thank you!

**Comment by adamschwartz** [comment]
This is something that should just work if the carousel contents are contained within the dialog. It’s hard to say what could be wrong without seeing the full picture. Would you mind sharing a jsFiddle or live page somewhere where we can see the broken functionality?

**Comment by cecilylomein** [comment]
Thanks for getting back to me-- here's a jsfiddle that shows what I mean. For context, I want to have multiple icons (.work-obj) that open vex dialogs when clicked, each with different html in their hidden divs (.work-dialog). 


http://jsfiddle.net/qx7e550a/10/

**Comment by adamschwartz** [comment]
Just initialize the carousel in the vex:
http://jsfiddle.net/adamschwartz/qx7e550a/11/

Since you were setting the html text as the inside of the vex, the copy of the carousel inside vex was not the one you initialized before opening the dialog.

**Comment by cecilylomein** [comment]
it works perfectly, thanks again!!
