### ISSUE TITLE
About file structure changed

### ISSUE THREAD

**Issue by pvnr0082t** [HubSpot/vex#165]
Hi @adamschwartz ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team. I found that file structure changed in `v3.0.0-beta.1`. I'd like to discuss if it's possible to also put `css` folder into `dist` folder. Thanks.

https://github.com/cdnjs/cdnjs/issues/8710
https://github.com/cdnjs/cdnjs/pull/8723

**Comment by bbatliner** [comment]
@adamschwartz @geekjuice I updated the directory structure in f923e64 with the new `/dist/{css,js}/*.{css,js}` structure that other HubSpot open source projects use. Can you rebuild the docs/make sure I updated all of the paths correctly? I'll also be more mindful in the future not to commit directly to `master` all of the time haha.

I also found the bower.json and component.json files and was wondering if we're still interested in publishing vex to those package managers, too.

@pvnr0082t We are updating the file structure to work with cdnjs, putting the `css` folder inside of `dist`. Once we release 3.0.0 out of beta, it should be good to go with cdnjs. Thanks!

**Comment by bbatliner** [comment]
Think we're good here. File structure change was made as specified in August, and cdnjs seems to be pulling the right files in its repo.
