### ISSUE TITLE
onSubmit callback undocumented?

### ISSUE THREAD

**Issue by plauclair** [HubSpot/vex#167]
Hey, good job on the plugin. It took me a while to figure out the flow of it but I got it in the end.

I've had to override the `onSubmit()` on the dialogs (`vex.dialog.open` doing an AJAX login script with multiple other dialogs to handle errors and whatnot).

At first I had a feeling that `callback()` was where to put the logic, but turns out it's not. `beforeClose()` isn't of much help since preventing `close()` by returning false from it of course would put it in a callback loop. So the really clean way is to remove the `return this.close()` from the default settings.  Of course you know all of this, I'm just leaving this here for people who would have trouble getting the hang of it too.

I was wondering, is the lack of onSubmit documentation intentional? Is it supposed to be discarded at a later time?

Also I don't see a roadmap, but I get the feel that there's a lot more to come, am I right? I could help out on the effort since I feel I'll be using it a lot more in the coming months and will probably make it an 'internally supported' library at work. If you could share a roadmap, that would be really helpful to ensure we'd go in the same direction. Cheers!

**Comment by bbatliner** [comment]
Thanks for the support, @plauclair!

You're right, `onSubmit` is undocumented. I found it odd, when I went back and looked at the code, that it's a default option and can be overridden. Considering it's responsible for serializing the form and preventing the refresh of the page that would come with a form submit, I'd say this logic probably shouldn't be overrideable. The code will ship as-is in 3.0.0 but can you open an issue so we can resolve this in the future?

I had trouble following your use case and why the different callbacks weren't meeting your needs. Can you explain this again?

With regards to a roadmap, there's nothing official, but I'm personally interested in #133 and accessibility of vex as a logical "next step" for the project. vex 3 was primarily a cleanup/rewrite of the original vex code, and should be much easier to build upon moving forward. I'd love to see you be involved and thank you for offering your time!

**Comment by plauclair** [comment]
I'm doing XHR on submit, and the default onSubmit would just submit the form and close the window. So I'm catching its default event and inserting things in it, then emulating default behavior when necessary.

Here's a git of the implementation, you'll most likely only be interested in the onSubmit parts.
https://gist.github.com/plauclair/5cd29a21490d562bb4d77f65636de88f

**Comment by riggerthegeek** [comment]
Would it not be better to allow `beforeClose` to resolve/reject a promise then `onSubmit` could be deprecated without losing the async validation functionality?

**Comment by mekeor** [comment]
I'm having the same issue with the default implementation of `onSubmit`; namely, it closes the whole window. And so far, I couldn't figure out how to stop it. So, at least some documentation would be nice!
