### ISSUE TITLE
vex dialog not closing when it should

### ISSUE THREAD

**Issue by EWalkerDev** [HubSpot/vex#170]
I have a simple vex confirm dialog.
But when I click "ok" the dialog doesn"t close.
Is theyre a way to programmaticaly close a dialog  ?

I tried "
var vexDlg=vex.dialog.confirm({
...
):
vex.close(vexDlg.data().vex.id);" 

but without success

**Comment by bbatliner** [comment]
Is there an error that appears in the console?

**Comment by EWalkerDev** [comment]
Yes effectively, I didn't notice, the problem was in my code.
 
I would also like to know how to allow "empty fields", In my dialog box with a text field
 
Regards
Eric Walker
 
 
 
 
> Message du 22/08/16 20:56
> De : "Brendan Batliner" 
> A : "HubSpot/vex" 
> Copie à : "EWalkerDev" , "Author" 
> Objet : Re: [HubSpot/vex] vex dialog not closing when it should (#170)
> 
>
> Is there an error that appears in the console?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/HubSpot/vex","title":"HubSpot/vex","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/HubSpot/vex"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bbatliner in #170: Is there an error that appears in the console?"}],"action":{"name":"View Issue","url":"https://github.com/HubSpot/vex/issues/170#issuecomment-241513887"}}}

**Comment by bbatliner** [comment]
I'm not sure what you mean by empty fields. If this is still an issue, please create a new issue. Thank you for using vex!
