### ISSUE TITLE
vex.combined.min.js:2  Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by 81552433qqcom** [HubSpot/vex#171]
Dear All,

Dose vex requires jQuery? One of our site has show this issue...

Is there any workaround?

**Comment by 81552433qqcom** [comment]
its version: /*! vex.js, vex.dialog.js 2.2.1 */

**Comment by bbatliner** [comment]
Yes, vex 2 requires jQuery to be included on the page before vex. If you can upgrade to vex 3 (`npm install vex-js@3.0.0-beta1` or check the GitHub releases), the jQuery dependency was dropped and you will be able to use vex without jQuery. Let me know if you have any questions about setting up vex!
