### ISSUE TITLE
Multiple buttons

### ISSUE THREAD

**Issue by BC17** [HubSpot/vex#178]
Hello I try to achieve to get multiple buttons on vex.open, here is my code (from  https://jsfiddle.net/adamschwartz/Lrq84/) : 

`var v = vex.dialog.open({
				    message: 'Le devis sera définitivement refusé. Veuillez sélectionner le motif du refus : ',	   

				    buttons: [
				        $.extend({}, vex.dialog.buttons.NO, { className: 'vex-dialog-button-primary-horizontal', text: 'Refus cause tarif', click: function($vexContent, event) {
				            $vexContent.data().vex.value = 'Tarif';
				            vex.close(v);
				        }}),
				        $.extend({}, vex.dialog.buttons.NO, { className: 'vex-dialog-button-primary-horizontal', text: 'Refus cause dispo hôtel', click: function($vexContent, event) {
				            $vexContent.data().vex.value = 'Dispo hôtel';
				            vex.close(v);
				        }}),
				        $.extend({}, vex.dialog.buttons.NO, { className: 'vex-dialog-button-primary-horizontal', text: 'Refus cause dispo thalasso', click: function($vexContent, event) {
				            $vexContent.data().vex.value = 'Dispo thalasso';
				            vex.close(v);
				        }}),
				        $.extend({}, vex.dialog.buttons.NO, { className: 'vex-dialog-button-primary-horizontal', text: 'Changement avis', click: function($vexContent, event) {
				            $vexContent.data().vex.value = 'Changement avis';
				            vex.close(v);
				        }}),
				        $.extend({}, vex.dialog.buttons.NO, { className: 'vex-dialog-button-secondary-horizontal', text: 'Annuler', value:'', click: function($vexContent, event) {
				            $vexContent.data().vex.value = false;
				            vex.close(v);
				        }})
				    ],
				    callback: function(value ) {
				        console.log('Choice', value);
				});`

I get this error : $vexContent.data is not a function

Can you help ?

**Comment by jdmoliner** [comment]
This works for me:

```
$.extend({}, vex.dialog.buttons.NO, { className: 'vex-dialog-button-primary-horizontal', text: 'Refus cause tarif', click: function(e) {
                        this.value = 'Tarif';
                        this.close();
                    }}),
```

**Comment by BC17** [comment]
Thank you very much JD, it works.

This should be in docs...
