### ISSUE TITLE
vex.close()/vex.closeAll() fires as cancel

### ISSUE THREAD

**Issue by Alessio92** [HubSpot/vex#179]
Hi, this is my current situation:
The page shows the vex modal and informs the user about the remote changes.
"Ok": keeps the changes, updates the local cache.
"Cancel": overrides the remote changes with my local cache.
If changes increase but user doesn't click the "ok/cancel" button the dialog box must be closed and the new one have to be showed with the new changes.

I tried the vex.close() function but the "cancel" callback fires, causing trouble.
I think that is not the correct way to close the dialog, is it?
How i have to proceed?

I use vex version 2.3.4

**Comment by bbatliner** [comment]
Hello, in the latest versions of vex there is one callback, `callback`, which indicates if the dialog was OK'd or cancelled. Please upgrade and thank you for using vex!
