### ISSUE TITLE
Modal dialog not working with scrollbar

### ISSUE THREAD

**Issue by mazing** [HubSpot/vex#183]
When having a lot of content in an `vex.dialog.alert()`, a scrollbar appears (which is great), but it starts in the bottom, so the user has to scroll up to see the dialog from the beginning.

Also, the faded background (and option to click to close the dialog) only covers 100% height, but since there is a scrollbar, the height of the modal is much bigger than 100% of the window.

The modal dialogs in, for instance, Bootstrap work fine with scrollbars. I guess it's a minor css problem, but I am not very good at css.

**Comment by mazing** [comment]
I have just tried with `plain` theme. There, the background is correct, but the window still begins in the bottom of the scrollbar instead of at the top.

So there is a bug with the background in the `flat-attack` theme.

**Comment by galacticevil** [comment]
To resolve the issue where the dialog content starts at the bottom, when setting your options use `focusFirstInput: false,`, that did the trick for me.

**Comment by neuquen** [comment]
@galacticevil 

Could you be more explicit with how to add `focusFirstInput: false` ?

I tried to define that value first before calling vex.dialog.confirm like so, but it doesn't work:

    vex.defaultOptions.focusFirstInput = false;
    vex.dialog.confirm({...})

**Comment by galacticevil** [comment]
@neuquen - I create a dialog with a lot of content so the issue where the content starts at the bottom was a problem for me. I had to set the `focusFirstInput` when opening the dialog for this to work. I also attached to the `afterOpen` and `afterClose` events to prevent the body from scrolling whilst the dialog is open - but this isn't necessary for the fix:

```
var $dialog = vex.dialog.open({
                unsafeMessage: htmlContent,
                buttons: [
                    $.extend({}, vex.dialog.buttons.YES, {
                        text: 'Done'
                    })
                ],
                focusFirstInput: false,
                showCloseButton: true,
                afterOpen: function() {
                    $('body').css('overflow', 'hidden');
                },
                afterClose: function() {
                    $('body').css('overflow', '');
                }
            });
```

Hope this helps.

**Comment by neuquen** [comment]
@galacticevil Thanks!  That worked great!

**Comment by rwasa** [comment]
@galacticevil  unfortunately that didn't work for me. Do you ever use the $dialog variable? If so where and how?

**Comment by bbatliner** [comment]
Cleaning house... a solution seems to have been given.
