### ISSUE TITLE
Prompt not accepting empty value

### ISSUE THREAD

**Issue by mazing** [HubSpot/vex#184]
It seems the prompt doesn't accept empty values.

If I input an empty value, the variable in the callback function is `undefined`, which is the exact same behaviour as if I had cancelled/closed the modal dialog without pressing OK.

It is thus not possible to distinguish cancel from OK when the input is empty.

**Comment by jorgerobles** [comment]
`vex.dialog.open({
            message,
            input: `<input name="prompt" type="text" placeholder="${placeholder}" value="${placeholder}"required />`,
            buttons: [
                $.extend({}, vex.dialog.buttons.YES, { text: 'Ok' }),
                $.extend({}, vex.dialog.buttons.NO, { text: 'Cancel' })
            ],
            callback: function (data) {
                if (!data) {
                    callback(null)
                } else {
                   callback(data.prompt)
                }
            }
        })`

**Comment by bbatliner** [comment]
```javascript
vex.dialog.prompt({
    callback (data) {
        console.log(data)
    }
})
```

With the latest version of vex, this is no longer an issue. `data` is `false` when the prompt is cancelled and `''` when the prompt is submitted with no content, as expected.
