### ISSUE TITLE
Apply input CSS also to select

### ISSUE THREAD

**Issue by mazing** [HubSpot/vex#185]
Wouldn't it be useful to style `<select><option ...></option></select>` with the same style as inputs?

I don't know if it's useful for many, but I am both using simple inputs but also select inputs, so instead of styling them myself, it would be great if the style applied to `<input>` was also applied to `<select>`.

This change would be really good if the library also had pre-built dialogs with `<select>` just like `prompt`, but since the style is already applied to `<textarea>`, I think it should also be applied to `<select>`

**Comment by KashyapAnshul** [comment]
give them the same class and define the class in css , it help

**Comment by mazing** [comment]
I know that I could just add

    .vex.vex-theme-flat-attack .vex-dialog-form .vex-dialog-input select

to line 226 in https://github.com/HubSpot/vex/blob/master/dist/css/vex-theme-flat-attack.css#L226, but it was a suggestion to make it more consistent in the library
