### ISSUE TITLE
vex combined prompt won

### ISSUE THREAD

**Issue by rajzik** [HubSpot/vex#190]
When you try demo in [docs](http://github.hubspot.com/vex/docs/welcome/) there prompt option which only works when you click on OK.
IE debugger returns 
``` javascript
// value = false
value = value[Object.keys(value)[0]]
Object.keys: argument is not an Object
```
IE 11 
Error on line 1202

**Comment by bbatliner** [comment]
To the best of my knowledge, [Object.keys is supported in IE11](https://kangax.github.io/compat-table/es5/#test-Object_static_methods_Object.keys_a_href=_https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys_title=_MDN_documentation_img_src=_../mdn.png_alt=_MDN_(Mozilla_Development_Network)_logo_width=_15_height=_13_/_/a_nbsp;). Closing...
