### ISSUE TITLE
diferents buttons in promp alert

### ISSUE THREAD

**Issue by joeldelvalle** [HubSpot/vex#191]
When I add new buttons in the callback I coundn't fine a way to identify wich button was clicked

buttons: [
        $.extend({}, vex.dialog.buttons.NO, { text: 'Cancelar' }),
        $.extend({}, vex.dialog.buttons.YES, { text: 'FC' }),
        $.extend({val: 'FP'}, {val: 'FP'}, { text: 'FP' })
      ],

is possible to do that?  how?

regards

**Comment by Yakoot** [comment]
Coffeescript:
```
buttons: [
        $.extend {}, vex.dialog.buttons.YES,
          className: 'vex-dialog-button-primary'
          text: 'First'
          click: (e) ->
            this.value = 'first'
            
        $.extend {}, vex.dialog.buttons.YES,
          className: 'vex-dialog-button-primary'
          text: 'Second'
          click: (e) ->
            this.value = 'second'
      ]
```

and catch the value in the callback.

**Comment by joeldelvalle** [comment]
Tks!!!
