### ISSUE TITLE
Documentation says there are no requirements but this requires jQuery!

### ISSUE THREAD

**Issue by Good4m** [HubSpot/vex#194]
https://github.com/HubSpot/vex/blob/master/docs/intro.md

"vex.combined.min.js:2 Uncaught ReferenceError: jQuery is not defined"

**Comment by bbatliner** [comment]
Which version of vex are you using? The latest, vex 3, requires nothing. Earlier major versions will require jQuery to be included beforehand.

**Comment by Good4m** [comment]
2.3.3

**Comment by Good4m** [comment]
I will try the new version thank you for the extremely fast response!
