### ISSUE TITLE
HTML message

### ISSUE THREAD

**Issue by alphaville** [HubSpot/vex#196]
Can I create a dialog with a message in HTML? For example, if I try to include HTML code in `message`:

```{.js}
vex.dialog.alert({
      message: 'hello <strong>world</strong>',
      className: 'vex-theme-flat-attack'
    })
```

I get the message `hello &lt;strong&gt;world&lt;/strong&gt;`.

**Comment by alphaville** [comment]
I found out that I should be using `vex.dialog.open` instead, so I'm closing this issue.

**Comment by milosb793** [comment]
Hey @alphaville , I'm using `vex.dialog.open` too, and can see escaped HTML. 

EDIT: I've found that in order to see HTML properly, the flag `unsafeMessage` should be used instead of only `message`. Example:

```js
 vex.dialog.open({
      overlayClosesOnClick: false,
      unsafeMessage: messageHtml
 })
```
