### ISSUE TITLE
return false not work on onSubmit function?

### ISSUE THREAD

**Issue by xiranst** [HubSpot/vex#197]
there is my code:

`
$('input[name="submitOrder[invoice]"]:radio').change(function () {
        var me = $(this);
        if (me.val() === 'yes')
        {
            vex.dialog.open({
                message: 'Enter your username and password:',
                input: [
                    '<input name="username" type="text" placeholder="Username" required />',
                    '<input name="password" type="password" placeholder="Password" required />'
                ].join(''),
                buttons: [
                    $.extend({}, vex.dialog.buttons.YES, { text: 'Login' }),
                    $.extend({}, vex.dialog.buttons.NO, { text: 'Back' })
                ],
                callback: function (data) {},
                onSubmit: function (data) {
                    return false
                }
            });
            return false;
        }
        return false;
    });
`

once click submit button, the popup windows will be closed and the current page was refreshed. why? 
i need to check the data. if data is wrong, the popup windows should be open not close. if data is right, the popup windows will be close and not refresh the current page.
how to do it?

**Comment by bbatliner** [comment]
The default `onSubmit` function (if you don't provide one) looks like this:

```js
onSubmit: function onDialogSubmit (e) {
  e.preventDefault()
  if (this.options.input) {
    this.value = serialize(this.form, { hash: true })
  }
  return this.close()
}
```

If you remove your custom `onSubmit`, I was able to see the username and password data in the `callback`.

**Comment by bbatliner** [comment]
Here is the code I used:

```js
$('input[name="submitOrder[invoice]"]:radio').change(function () {
    var me = $(this);
    if (me.val() === 'on') {
        vex.dialog.open({
            message: 'Enter your username and password:',
            input: [ '<input name="username" type="text" placeholder="Username" required />', '<input name="password" type="password" placeholder="Password" required />' ].join(''),
            buttons: [
                $.extend({}, vex.dialog.buttons.YES, { text: 'Login' }),
                $.extend({}, vex.dialog.buttons.NO, { text: 'Back' })
            ],
            callback: function (data) {
                console.log(data)
            }
        });
        return false;
    }
    return false;
});
```

**Comment by bbatliner** [comment]
Closing to clean up. The `onSubmit` handler will be your best bet to validate the form data.
