### ISSUE TITLE
vex dialog not working

### ISSUE THREAD

**Issue by paparupps** [HubSpot/vex#208]
I am using Vex successfully on several pages of the web app I am developing.  However, in this particular screen, the vex dialog is not working as expected.  The picture shows how all the vex dialogs are appearing on my screen.  Then, no matter which of the buttons are clicked, 'value' is set to false.  I'm thinking theres' something in my code (which is rather extensive) that is interfering with Vex, but I haven't been able to figure it out.  Has anyone else ever run into this ?

**HTML code**

<link rel="stylesheet" href="css/vex.css" />
<link rel="stylesheet" href="css/vex-theme-os.css" />

<script src="js/vex.combined.min.js"></script>
<script>vex.defaultOptions.classname = "vex-theme-os"</script>

**JAVASCRIPT coding in Cancel button.**

			vex.dialog.open({
				message: 'Discard changes ?',
				showCloseButton: false,
				buttons: [
					$.extend({}, vex.dialog.buttons.YES, { text: 'Yes' }),
					$.extend({}, vex.dialog.buttons.NO, { text: 'No' })
				],
				callback: function (value) {
					if (value){
                                               // Do stuff
					}
				}
			});

![image](https://cloud.githubusercontent.com/assets/26122016/23475026/00f9f27a-fe84-11e6-8793-ddc2a4c24298.png)

**Comment by bbatliner** [comment]
It looks like the vex dialog on this page doesn't have a theme. Make sure to include the CSS at the top of the page!

**Comment by paparupps** [comment]
Sorry - I should have included all of the contents of the head.  

<link rel="stylesheet" type="text/css"  href="../common/css/pako_combo.css" />
<link rel="stylesheet" type="text/css" href="../common/css/jquery.alerts.css" media="screen"/>
<link rel="Stylesheet" type="text/css" href="../common/css/jquery-ui.css"/>
<link rel="stylesheet" type="text/css" href="../common/css/datepicker.css">

<link rel="stylesheet" href="../common/css/vex.css" />
<link rel="stylesheet" href="../common/css/vex-theme-os.css" />

<link rel="stylesheet" type="text/css" href="css/ordermaint_css.css" /> 

<script type="text/javascript" src="../common/js/jquery.min.js"></script>
<script type="text/javascript" src="../common/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="../common/js/pako_pageframe_tabs.js"></script>
<script type="text/javascript" src="../common/js/pako_combo.js"></script>
<script type="text/javascript" src="../common/js/pako_cookies.js"></script>
<script type="text/javascript" src="../common/js/pako_functions.js"></script>
<script type="text/javascript" src="../common/js/moment.js"></script>
<script type="text/javascript" src="../common/js/jquery.alerts.js"></script>

<script src="../common/js/vex.combined.min.js"></script>
<script>vex.defaultOptions.className = "vex-theme-os"</script>
