### ISSUE TITLE
Flashes on Close in Internet Explorer

### ISSUE THREAD

**Issue by mike-ward** [HubSpot/vex#216]
To reproduce, run the demo in Internet Explorer 11. On close, the dialog flashes for a moment after closing.

**Comment by mike-ward** [comment]
Interesting, adding this to my style sheet fixes the issue:

    .vex.vex-closing .vex-content {opacity: 0;}
    .vex.vex-closing .vex-overlay {opacity: 0;}

**Comment by bbatliner** [comment]
Fixed in #233
