### ISSUE TITLE
Release 3.1.1

### ISSUE THREAD

**Issue by bbatliner** [HubSpot/vex#218]
Changes:
 - Update vex-dialog from 1.0.6 -> 1.0.7
   - Fixes a few bugs.
     - `select` elements can be autofocused
     - Button `className` options are backwards compatible with vex 2.
     - `prompt` now correctly returns `false` on cancel

@adamschwartz Can we release 3.1.1 on npm? I will create the git release.

**Comment by adamschwartz** [comment]
Done.
