### ISSUE TITLE
Options documentation

### ISSUE THREAD

**Issue by strohhut** [HubSpot/vex#221]
I cannot find information  in the documentation about all the options that can be passed to the `open`
 function like custom button settings ` buttons: [{type: '...', text: '...', className: '...'}]`. 

For instance I know that there is a `confirm` type because I found that somewhere on jsfiddle but I don't know the other types.

**Comment by bbatliner** [comment]
The `type` option is used to set the DOM attribute `type`. Read more about button attributes: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

`type`, `text`, and `className` are the only three button options and they're used as you expect. I added some documentation in 8a914d9, does it look good?

**Comment by strohhut** [comment]
Yes, thanks for adding this to the docs.
