### ISSUE TITLE
HTML Not implemented when unsafeContent set

### ISSUE THREAD

**Issue by bharal** [HubSpot/vex#226]
Using the unsafeContent parameter does not work with the minifed version.

This code

var d=c.unsafeContent=f(c)

seems to be the culprit, removing the call to f(c) returns unsafeContent to appearing.

I don't see this in the source code, so I'm unsure what the minimized version is pulling to show this.

Also, the test if(a.unsafeContent&!a.content) is ambiguous, and it isnt specified in the docs that setting content and unsafeContent ignores the unsafe content entirely. Better would be to have an unsafeContent flag if you're doing this, as it makes clear what your intentions are. Well, make an unsafeContentFlag flag, so that older versions are still compatible with the flag.

**Comment by bbatliner** [comment]
This is because vex-dialog uses different options - `message` and `unsafeMessage`. See my comment [here](https://github.com/HubSpot/vex/issues/220#issuecomment-302896433). There might be more we can do to improve the documentation surrounding this option.
