### ISSUE TITLE
`$.extend` in doc needs jQuery

### ISSUE THREAD

**Issue by benomatis** [HubSpot/vex#228]
The doc refers to a jQuery plugin function `$.extend` even though it claims to be independent. You may want to "extend" (pun not intended) the script so it uses vanilla js for that.

Example: 
```js
var extend = function(out) {
  out = out || {};

  for (var i = 1; i < arguments.length; i++) {
    if (!arguments[i])
      continue;

    for (var key in arguments[i]) {
      if (arguments[i].hasOwnProperty(key))
        out[key] = arguments[i][key];
    }
  }

  return out;
};

extend({}, objA, objB);
```

Source: http://youmightnotneedjquery.com/#extend

**Comment by bbatliner** [comment]
`$.extend` is used in the docs, but the library itself does not depend on jQuery. The docs also recommend [html-escape](https://www.npmjs.com/package/html-escape) and [_.escape](https://lodash.com/docs#escape) for HTML content.

I agree, a better replacement would be `Object.assign`, the vanilla ES6 version of extend. Feel free to change the docs and make a PR if you want to see the change.

**Comment by benomatis** [comment]
I might be missing something, but haven't you mixed up `extend` with `escape`...?

**Comment by bbatliner** [comment]
I'm saying the docs make use of external libraries and try to point out where they do so. jQuery for some utility stuff and other modules for HTML escaping. Vex core does not have any dependencies.
