### ISSUE TITLE
Submit Form ( POST ) after Button Clicked 

### ISSUE THREAD

**Issue by marcoczen** [HubSpot/vex#229]
Hi,

I have a bootstrap form with a submit button as below;

``
<button type="submit" class="btn btn-primary" name="button_deluser" > Delete Selected User </button>
``

When the button is clicked - the form is submitted. I would like a confirmation box (Yes - Delete, No ).
I dont understand how to incorporate vex confirm into the button above from the documentation provided.

Any ideas ? Alert - Jquery newbie here.

**Comment by Timur2012** [comment]
All you need to do is set an on click function for the button, and define that function in your javascript. The function can then call the vex confirm dialog and do something with that value.

For example:
```
<body>
        <button type="submit" onclick="buttonFunction()"> Delete </button>
</body>
<script>
         function buttonFunction() {
            vex.dialog.confirm({
                message: 'Do you want to delete this user?',
                className: 'vex-theme-plain',
                callback: function(value) {
                    // Value is a boolean here, so add your logic for deleting the user here
                }
            })
       }
</script>
```

**Comment by bbatliner** [comment]
Just because this is an old issue, I'm going to close it because @Timur2012's solution works (prevent the form submit in JS, confirm with vex and submit programmatically). Thanks!
