### ISSUE TITLE
Can't resolve 'vex-js/js/vex.dialog'

### ISSUE THREAD

**Issue by kaihendry** [HubSpot/vex#232]
I am trying to get code using vex-js to work after an update which includes webpack et al.

Code not written by myself looks like: `import dialog from "vex-js/js/vex.dialog"`

Which results in a `Module not found: Error: Can't resolve 'vex-js/js/vex.dialog'`

In the `webpack.config.js` there is a:

```
        resolve: {
                alias: {
                        vex: 'vex-js',
                },
        },
```

Which I could swear used to work.

Has the way using vex-js changed?

**Comment by kaihendry** [comment]
Furthermore I have these imports that seem to be failing:

```
static-website$ grep vex assets/styles/client.css
@import "./../../node_modules/vex-js/css/vex.css";
@import "./../../node_modules/vex-js/css/vex-theme-plain.css";
@import "./vex.css";
```

Any ideas how to best import CSS in a Webpack build?

**Comment by bbatliner** [comment]
What version of vex are you using? In versions 3.0.0 and up, the main files are located at: `vex-js/dist` and then in `css` and `js` folders.

**Comment by kaihendry** [comment]
In my package.json I've got "vex-js": "^4.0.0", but previously I think it was a pretty ancient version.

**Comment by bbatliner** [comment]
I would change the imports/resolves (not familiar with Webpack terminology, sorry) to point to the new file locations. Let me know if that works.

**Comment by bbatliner** [comment]
Did that work?
