### ISSUE TITLE
vex's HubSpot site isn't updating

### ISSUE THREAD

**Issue by PikadudeNo1** [HubSpot/vex#234]
The official docs at http://github.hubspot.com/vex/ haven't updated since version 3.0.0. This is especially concerning now that version 4 has changed the DOM structure, but http://github.hubspot.com/vex/api/advanced/ is showing the old one.

**Comment by bbatliner** [comment]
@adamschwartz I may have permission to publish on npm, but I believe someone internal to HubSpot needs to rebuild the docs from this repo. Can we update those?

**Comment by adamschwartz** [comment]
I’d love to help! But unfortunately as I have not worked at HubSpot since 2014 I no longer have access to the `HSDocs` tool which builds the docs for this project. Someone here should be able to help: https://github.com/orgs/HubSpot/people

**Comment by timmfin** [comment]
I should be able to look into in this weekend. Sorry for the delay!

**Comment by timmfin** [comment]
I pushed out updated docs, but it doesn't look like there were any documentation changes made in the repo during/after the 4.0.0 release. Do any docs need to be changed?

I'm happy to push out a docs update again if/when anything is changed.

**Comment by PikadudeNo1** [comment]
Dunno what you mean by "no documentation changes"; the new DOM structure was documented, and that's now reflected at http://github.hubspot.com/vex/api/advanced/ , so we're all good there.

However, the site's <title>s and <h1>s now say "vex-os" instead of just "vex".

**Comment by timmfin** [comment]
Apologies. I only looked around the commits in the 4.0 PR and _thought_ I didn't see any markdown changes (I'm out of touch with this repo and totally missed the two line doc change: https://github.com/HubSpot/vex/commit/104a60a9999f965f22ced3ab712f1ff109ef0924#diff-2d9cabdfa28d8138aed4d55c870d2339L9). 

I'll fix the vex-os bit shortly.
