### ISSUE TITLE
Use Autoprefixer instead of prefixing mixins

### ISSUE THREAD

**Issue by PikadudeNo1** [HubSpot/vex#236]
Currently, when using CSS properties or at-rules that need vendor prefixes, this project uses Sass mixins that compile to all possible variants. This has drawbacks:

* The Sass source is harder to write, as it's difficult to remember which properties/at-rules have a mixin available.
* The compiled CSS is harder for developers making consuming applications to read, as it's bloated with many unnecessary variants. For example, no Microsoft browser has ever needed `-ms-` for any animation-related property or at-rule, yet vex provides every `@keyframes` a matching `@-ms-keyframes` rule.

IMO, a much better approach is to use [Autoprefixer](https://github.com/postcss/autoprefixer), which analyzes the CSS after Sass has done its work and adds only the prefixes needed according to the specified [browserslist](https://github.com/ai/browserslist). I'm willing to do the work to migrate this project to Autoprefixer and submit a PR; I'd just like some indication that the work will be welcome.

This would entail a few things:
* Autoprefixer, PostCSS, and anything else necessary would become devDependencies of this project.
* vex's supported browsers would be formally specified in package.json. I plan on copying the versions over from the Browser Support section of [the home page](http://github.hubspot.com/vex/).

**Comment by bbatliner** [comment]
I've used similar tools in other projects, big fan. When I rewrote vex last year I focused on the JS because that was my expertise. An upgrade of the CSS side would be greatly appreciated! Thanks so much pikadude. Let me know how I can help.

**Comment by PikadudeNo1** [comment]
Thanks for the positive response; I'll gladly get that done!

I have a question I hope you can answer: Is `pie-clearfix` (defined in _mixins.sass and used in vex-theme-*.sass) still needed for IE 9+? If it turns out it isn't, we can drop the entire _mixins.sass file.
