### ISSUE TITLE
How to integrate the tinymce editor in open windows?

### ISSUE THREAD

**Issue by xiranst** [HubSpot/vex#240]
same the title. how to interagency the tinymce editor when open a window? i add tinymce.init({selector: '.tinymce'}); in the afterOpen function.  there has one question:
the form can not be submit when click submit button. i have filled content into the editor but the textear can not get the content, so form not be submit;

**Comment by bbatliner** [comment]
'but the texture can not get the content', what do you mean by this?

**Comment by xiranst** [comment]
@bbatliner sorry my typo. that is the textarea can not get the content from tinymce. please check the attachment.

<img width="438" alt="11984791-8f99-4708-a13b-bc647178142b" src="https://user-images.githubusercontent.com/9444008/30237959-2c0b5b56-9570-11e7-8757-6db97bede5fe.png">

<img width="624" alt="8b9a3fd8-79e1-48ac-b405-460228328c59" src="https://user-images.githubusercontent.com/9444008/30237965-382e65d6-9570-11e7-94f4-e4932f415e32.png">

because the textarea value is required, so this form can not be submitted. i try to alert some value in vex.onSubmit that is not working.

<img width="397" alt="3700744c-4b5d-4998-9f53-a7c2dd468b24" src="https://user-images.githubusercontent.com/9444008/30237987-80f14568-9570-11e7-9843-83991bb46835.png">

**Comment by bbatliner** [comment]
I can't remember why vex-dialog uses a form at the moment, so in the meantime let's work around it.

Could you add another line of code to `afterOpen` that removes the required attribute from the hidden textarea? Something like:

```javascript
$('#form_template_block_html').removeAttr('required')
```

**Comment by xiranst** [comment]
@bbatliner i add form into vex-dialog to save some works for user. i have removed the required attribute for textarea, but the form is still not submitted and the alert is not working in onSubmit funciton. maybe this question is about the tinymce and i will ask tinymce. thanks for your help.

**Comment by bbatliner** [comment]
![image](https://user-images.githubusercontent.com/5896658/30238073-4cb424b6-9505-11e7-916a-58ee1e142d1e.png)

I mean the vex popup has a form inside of it, which could be messing with the submitting. Ok, let me know what you find out.

**Comment by xiranst** [comment]
@bbatliner yes, i know the form in vex popup.

**Comment by xiranst** [comment]
@bbatliner i can submit the form data now. i remove the required attribute from php code not in vex. but the textarea must be required. so, i will research it again. thanks for your vex that is very nice plugin.
