### ISSUE TITLE
HubSpot site says "vex-os" in h1 & title elements

### ISSUE THREAD

**Issue by PikadudeNo1** [HubSpot/vex#244]
@timmfin (or anyone else from HubSpot with appropriate access), this seems to be one for you. http://github.hubspot.com/vex/ is saying "vex-os" in h1 & title elements when it should say just "vex"; I first reported this in a comment on issue #234, and it was fixed back then, but now seems to be unfixed again.

**Comment by timmfin** [comment]
Sigh. My bad... will be at a machine to fix later.

**Comment by timmfin** [comment]
Fixed.
