### ISSUE TITLE
Issue in the vex demo

### ISSUE THREAD

**Issue by plashenkov** [HubSpot/vex#246]
In the main demo: http://github.hubspot.com/vex/docs/welcome/

When trying to click "alert", "confirm", etc. in the third dialog box, they are not shown. They are hidden between all windows. That looks very strange.

**Comment by bbatliner** [comment]
Good catch! Fixed in 8b45d2a by moving all the examples to the top of the stack. Thanks!

@timmfin does this require rebuilding the docs to get the hubspot.com site to update?

**Comment by timmfin** [comment]
Docs are (finally) updated.
