### ISSUE TITLE
handler defined in onSubmit doesn't respond the first time event is fired 

### ISSUE THREAD

**Issue by sunilw** [HubSpot/vex#248]
I'm creating a simple password challenge.

Because I want the modal to not close automatically when a button within it is clicked, I'm creating logic within an onSubmit handler.

This is what I have:

 ```
vex.dialog.open({
                message: 'Password Please',
                input: [
                    '<input name="password" type="text" placeholder="password" required />',
                ].join(''),
                buttons: [
                    $.extend({}, vex.dialog.buttons.YES, { text: 'Password' }),
                ],
		onSubmit : function(e) {
		    e.preventDefault() ;
		    e.stopPropagation();	
		    
		    $(".vex-dialog-buttons button").on("click", function(e) {
			e.preventDefault() ;
			e.stopPropagation();	
			var value = $(".vex-dialog-input input").val() ;
			
			console.log(value);
			
		    }) ;		    
		}		
		
            }) ;
```

I expect that when the button is clicked, I'll get output to console.
This happens only from the second time and onward that the button is clicked.

This applies to any logic that I put inside the inner function: the first click seems to be ignored.

What could be happening here?

**Comment by michaelvdow** [comment]
I believe I found a solution to this problem. The issue was that the on click function would only be applied to the button after the first submit click, since this was placed inside it. Instead, you could directly get the value of the input using the following:

```
vex.dialog.open({
               message: 'Password Please',
               input: [
                   '<label>Password</label><input name="password" type="text" placeholder="password" required />',
               ].join(''),
               buttons: [
                   $.extend({}, vex.dialog.buttons.YES, { text: 'Password' }),
               ],
                onSubmit : function(e) {
                    console.log(this.form.querySelector('input').value);
                    e.preventDefault() ;
                    e.stopPropagation();
                },   	
           })
```

**Comment by bbatliner** [comment]
@michaelvdow suggested the most canonical way to do this with vex-dialog. The input value is available in `onSubmit` by querying the form. If the form is allowed to submit, the value will also be parsed and given to the `callback` function, if supplied as an option.
