### ISSUE TITLE
How to disable vex Submit with SPACE 

### ISSUE THREAD

**Issue by zMrSnow** [HubSpot/vex#254]
How to disable vex Submit with SPACE

**Comment by bbatliner** [comment]
Could you be more specific?

I think you're referring to the fact that if you press the spacebar after a dialog opens, it will close. This is a result of the `focusFirstInput` option for vex-dialog, which will autofocus the submit button (or another button) when the dialog opens. Then pressing space will click the button and the dialog will close.

Pass `focusFirstInput: false` to your dialog options and that should do it.
