### ISSUE TITLE
unsafeContent option not working

### ISSUE THREAD

**Issue by danielrvt** [HubSpot/vex#263]
The unsafeContent option does not seem to be working.

`  <script id="hidden-modal-template" type="text/html">

             <form class="vex-dialog-form">
                <div class="vex-dialog-message">
                        asdfsadfsdf
                </div>
               <div class="vex-dialog-input">
               </div>
               <div class="vex-dialog-buttons">
                   <button type="submit" class="vex-dialog-button-primary vex-dialog-button vex-first">Si</button>
                   <button type="button" class="vex-dialog-button-secondary vex-dialog-button vex-last">No</button>
               </div>
              </form>

        </script>

        <script type="text/javascript">
                $(document).ready(function() {
 
                   vex.defaultOptions.className = 'vex-theme-flat-attack';
        
                   if (!sessionStorage.isAdult) vex.dialog.confirm({
                        overlayClosesOnClick: false,
                        unsafeContent: $("#hidden-modal-template").html(), 
                        callback: function(res) {
                                  ...
                        }
                   });
                });
                
        </script>
`

The options message and content work fine, but I'm unable to load HTML content

**Comment by demkinmaxim** [comment]
I think you should use { unsafeMessage: ...} instead of unsafeContent...
