### ISSUE TITLE
More buttons on dialog

### ISSUE THREAD

**Issue by xkraty** [HubSpot/vex#34]
Hello,

i was trying your plugin and it works like a charm and i was wondering in the dialog there are the buttons YES/NO what if i'd need a button MAYBE or more buttons? For example if used in an e-commerce for quick basket purpose i could need 2 buttons checkout/continue shopping/view cart

**Comment by ghost** [comment]
This does not work, gives error $vexContent.data is not a function.  $vexContent comes in as a mouseEvent
