### ISSUE TITLE
Include complex HTML in dialog

### ISSUE THREAD

**Issue by pferrel** [HubSpot/vex#40]
I need to create a fairly complex modal sidebar for something like settings. I'd like to have is slide out from the left and remain in place attached to the left side of the viewport/window. The user will fiddle with settings and dismiss at some point. 

I can see how to do most of this but wonder about how to put the fairly complex HTML into the dialog.

**Comment by qodeboy** [comment]
Cloning HTML could produce duplicated IDs, which is bad and could introduce issues with other JS libraries or CSS. In my case, to warkaround this I wrapped up my templates into ```<script type="text/html"></script>``` and instead of cloning just doing ```$.html()```:

```js
$(document).on('click', '[data-vex-toggle="modal"]', function (e) {
        e.preventDefault();

        var $trigger = $(this);
        var $template = $('script[type="text/html"]#' + $trigger.data('template'));

        if (!$template.length) {
            return;
        }

        vex.open({
            content: $template.html(),
            className: 'vex-theme-default'
        });
    });
```
