### ISSUE TITLE
Title Text

### ISSUE THREAD

**Issue by Goiking** [HubSpot/vex#51]
It will be fantastic to have an option to give a title text for vex.

As example, if i use the vex-theme-os there is even for an Alert a grey bar on the top. I'd like to give some text to it.

![image](https://cloud.githubusercontent.com/assets/2844652/2696882/bbcb7eb4-c3e7-11e3-8b6c-aedc888f3b48.png)

**Comment by dileep021** [comment]
jsFiddle Demo is not working.

**Comment by adamschwartz** [comment]
@dileep021 try it now. 👍
