### ISSUE TITLE
Make JS snippets in docs more discoverable

### ISSUE THREAD

**Issue by caspark** [HubSpot/vex#63]
It's awesome that I can see the Javascript code samples with that little button on the top right of the docs site, but that button is super easy to miss. It was only after I'd downloaded and was looking through the source of the docs site to see how things worked that I noticed that it was there.

How about defaulting to Javascript and/or having the JS/Coffee buttons near each code sample?

**Comment by bbatliner** [comment]
The project is defaulted to Javascript now :) Hope this helps.
