### ISSUE TITLE
Allow preventDefault on events

### ISSUE THREAD

**Issue by dariusj18** [HubSpot/vex#66]
As far as I can tell, when binding to, say, "vexClose", there is no way to prevent the closing of the modal.

I am trying to add a confirmation dialog to closing a modal. For example:

```
vex.open({
    content: '<h1>I am content</h1><p>I will always ask if you are sure.</p>'
}).bind('vexClose', function(e, obj) {
    var closeID = $(this).data().vex.id;

    if(1 == 1) { // logic here to see if I need to ask
        vex.dialog.open({
            message: 'Are you sure you want to cancel?'
            , callback: function(value) {
                if(value) {
                    obj.closeById(closeID);
                }
            }
        });

        e.preventDefault(); // or return false
    }

});
```

Or something like that.

**Comment by bbatliner** [comment]
Good job @dariusj18 for figuring that out. We have the `beforeClose` lifecycle callback now that can synchronously prevent the dialog from closing, e.g. for validation reasons. An asynchronous version would have to be custom.
