### ISSUE TITLE
"Welcome" site in Chrome has odd behavior on last dialog

### ISSUE THREAD

**Issue by curtisk** [HubSpot/vex#77]
http://github.hubspot.com/vex/docs/welcome
On a 7" nexus in landscape mode, the demo works fine until that last dialog, what happens repeatedly is that it snaps to bottom left, so effectively when I then try to click the "X" to close it out, it thinks I'm hitting the twitter link
Chrome 37.0.2062.117

Edit: was playing around on tablet initially, when I got on laptop same deal under Chrome, 37.0.2062.120 m

**Comment by adamschwartz** [comment]
Though we already fixed this with a workaround, the underlying Chrome bug has now been fixed! https://code.google.com/p/chromium/issues/detail?id=426157 :)
