### ISSUE TITLE
How do I turn off the "pulsating" background color in the Vex Dialog Button in the demo?

### ISSUE THREAD

**Issue by tangst** [HubSpot/vex#94]
Hello, in the demo page http://github.hubspot.com/vex/api/basic/, when you click the alert demo, you see the Vex overlay with a blue OK button.  The blue color is "pulsating."  I need to turn that pulsating off in my implementation of Vex.  

Where is this controlled?  Thanks.

**Comment by geekjuice** [comment]
You should be able to control the 'pulsating' animation in the stylesheets. In particular, you can probably just remove [this line](https://github.com/HubSpot/vex/blob/master/sass/vex-theme-os.sass#L110) in the SASS file or [these lines](https://github.com/HubSpot/vex/blob/master/css/vex-theme-os.css#L462-L467) if you are using the compiled CSS files.

**Comment by tangst** [comment]
Thanks for the information.  I found the mentioned styles in the compiled CSS for the default theme and I was able to remove those lines.

**Comment by geekjuice** [comment]
:+1: No problem
