### ISSUE TITLE
Options to customize localization particular on dialog buttons

### ISSUE THREAD

**Issue by goldensunliu** [HubSpot/vex#99]
currently the dialog buttons are hard coded with English messages:

https://github.com/HubSpot/vex/blob/master/js/vex.dialog.js#L26

is there a way to customize dialog button messages or should I just fork the repo.

**Comment by adamschwartz** [comment]
You can customize the global variables if you want all dialog messages to be changed.

```coffeescript
vex.dialog.buttons.YES.text = 'Oui'
```

You can customize individual dialogs by passing in buttons with whatever text you’d like. See the [“Login” example in the documentation](http://github.hubspot.com/vex/).

**Comment by goldensunliu** [comment]
thanks!

**Comment by adamschwartz** [comment]
No problem, happy to help!
